---

- name: Ensure etcd PKI directory already exists
  file: path={{ etcd_pki_dir }} state=directory

- name: Check etcd ca SSL certificate json files
  stat:
    path: "{{ etcd_pki_dir }}/{{ item.bare }}.{{ cert_file_ext }}"
  with_items:
    - { file: etcd-ca-csr.json, name: etcd, org: etcd, bare: etcd-ca}
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: check_etcd_ca_json_files

- name: Generate etcd ca SSL certificate json files
  when: check_etcd_ca_json_files and not item.stat.exists
  template:
    src: noca-csr.json.j2
    dest: "{{ etcd_pki_dir }}/{{ item.item.file }}"
  with_items: "{{ check_etcd_ca_json_files['results'] }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: gen_etcd_json_files

- name: Check etcd SSL certificate json files
  stat:
    path: "{{ etcd_pki_dir }}/{{ item.bare }}.{{ cert_file_ext }}"
  with_items:
    - { file: etcd-csr.json, name: etcd, org: etcd, bare: etcd }
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: check_etcd_json_files

- name: Generate etcd SSL certificate json files
  when: check_etcd_json_files and not item.stat.exists
  template:
    src: noca-csr.json.j2
    dest: "{{ etcd_pki_dir }}/{{ item.item.file }}"
  with_items: "{{ check_etcd_json_files['results'] }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: gen_etcd_json_files

- name: Check etcd SSL certificate authority files
  stat:
    path: "{{ etcd_pki_dir }}/{{ item.bare }}.{{ cert_file_ext }}"
  with_items:
    - { file: etcd-ca-csr.json, ca: K8S-IM-CA, bare: etcd-ca }
  # stat:
  #   path: "{{ etcd_ca }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: check_etcd_ca_file

- name: Check etcd SSL CA json config
  stat:
    path: "{{ cache_dir }}/{{ item.bare }}-config.json"
  with_items:
    - { bare: etcd-ca }
    # - { bare: K8S-IM-CA }
  register: check_etcd_ca_config

- name: Generate etcd SSL CA config
  when: check_etcd_ca_config and not item.stat.exists
  template: src=ca-config.json.j2 dest="{{ cache_dir }}/{{ item.item.bare }}-config.json"
  with_items: "{{ check_etcd_ca_config['results'] }}"
  register: gen_etcd_ca_config

  # lupin 修改為 使用 自定中繼憑證 
- name: Ensure InterMediate PKI directory already exists
  when: check_etcd_ca_file and not item.stat.exists
  file: path={{ intermediate_dir }} state=directory
  with_items: "{{ check_etcd_ca_config['results'] }}"

- name: Copy InterMediate SSL certificate files
  when: check_etcd_ca_file
  copy:
    src: "{{ item.file }}"
    dest: "{{ intermediate_dir }}/{{ item.bare }}.{{ item.ext }}"
  with_items: 
    - { file: "files/K8S-IM-CA.{{ cert_file_ext }}", bare: K8S-IM-CA, ext: "{{ cert_file_ext }}" }
    - { file: "files/K8S-IM-CA-key.{{ cert_key_ext }}", bare: K8S-IM-CA-key, ext: "{{ cert_key_ext }}" }
    - { file: "files/K8S-IM-CA-bundle.{{ cert_file_ext }}", bare: K8S-IM-CA-bundle, ext: "{{ cert_file_ext }}" }
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

- name: Create etcd SSL certificate authority files
  when: check_etcd_ca_file and not item.stat.exists
  shell: |
    {{ bin_dir }}/cfssl gencert \
    -ca={{ intermediate_dir }}/{{ item.item.ca }}.{{ cert_file_ext }} \
    -ca-key={{ intermediate_dir }}/{{ item.item.ca }}-key.{{ cert_key_ext }} \
    -config={{ cache_dir }}/{{ item.item.ca }}-config.json \
    -profile=intermediate-ca \
    {{ etcd_pki_dir }}/{{ item.item.file }} | \
    {{ bin_dir }}/cfssljson -bare {{ etcd_pki_dir }}/{{ item.item.bare }}
  with_items: "{{ check_etcd_ca_file['results'] }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: create_etcd_ca_file

- name: Move cfssl etcd-ca cert file ext name
  when: check_etcd_ca_file and not item.stat.exists and cert_file_ext != "pem"
  command: "mv {{ etcd_pki_dir }}/{{ item.item.bare }}.pem {{ etcd_pki_dir }}/{{ item.item.bare }}.{{ cert_file_ext }}"
  with_items: "{{ check_etcd_ca_file['results'] }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: mv_etcd_ca_ssl_file
  ignore_errors: True

# 舊的生成自簽憑證 (RootCA)
# - name: Create etcd SSL certificate authority files
#   when: not check_etcd_ca_file.stat.exists
#   shell: |
#     {{ bin_dir }}/cfssl gencert -initca {{ etcd_pki_dir }}/etcd-ca-csr.json | \
#       {{ bin_dir }}/cfssljson -bare {{ etcd_pki_dir }}/etcd-ca
#   delegate_to: "{{ groups['masters'][0] }}"
#   run_once: true
#   register: create_etcd_ca_file

- name: Check etcd SSL certificate key file
  stat:
    path: "{{ etcd_pki_dir }}/{{ item.bare }}.{{ cert_file_ext }}"
  with_items:
    - { file: etcd-csr.json, ca: etcd-ca, bare: etcd }
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: check_etcd_ssl_file

- name: Create etcd SSL certificate key files
  when: check_etcd_ssl_file  and not item.stat.exists
  shell: |
    {{ bin_dir }}/cfssl gencert \
      -ca={{ etcd_pki_dir }}/{{ item.item.ca }}.{{ cert_file_ext }} \
      -ca-key={{ etcd_pki_dir }}/{{ item.item.ca }}-key.{{ cert_key_ext }} \
      -config={{ cache_dir }}/{{ item.item.ca }}-config.json \
      -hostname={{ etcd_hosts | trim }} \
      -profile={{ cert_info_profile }} \
      {{ etcd_pki_dir }}/{{ item.item.file }} | \
      {{ bin_dir }}/cfssljson -bare {{ etcd_pki_dir }}/{{ item.item.bare }}
  with_items: "{{ check_etcd_ssl_file['results'] }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: create_etcd_ssl_file

- name: Move cfssl etcd cert file ext name
  when: check_etcd_ssl_file and not item.stat.exists and cert_file_ext != "pem"
  command: "mv {{ etcd_pki_dir }}/{{ item.item.bare }}.pem {{ etcd_pki_dir }}/{{ item.item.bare }}.{{ cert_file_ext }}"
  with_items: "{{ check_etcd_ssl_file['results'] }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: mv_etcd_ssl_file
  ignore_errors: True