---

- name: Check SSL CA json config
  stat: path={{ ca_config }}
  register: check_ca_config

- name: Generate SSL CA config
  when: not check_ca_config.stat.exists
  template: src=ca-config.json.j2 dest="{{ ca_config }}"
  register: gen_ca_config

- include_tasks: create-k8s-certs.yml

- name: Copy ca certificate and key
  vars:
    files:
      - "{{ ca }}"
      - "{{ ca_key }}"
  import_role:
    name: common/copy-files

- include_tasks: create-k8s-kubelet-certs.yml

- include_tasks: create-etcd-certs.yml

# 這裡是刪除所有 .csr 及憑證設定檔 .json 若要長久使用同一憑證，這裡就不太適合刪除
# cert_info_expiry 的設定值為 87600h = 10 年
# 是否需要考慮改為 2160h = 3 月，並且定期加簽？
- include_tasks: purge-files.yml
