---

- include_tasks: create-k8s-certs.yml

- name: Copy ca certificate and key
  vars:
    files:
      - "{{ ca }}"
      - "{{ ca_key }}"
  import_role:
    name: common/copy-files

- include_tasks: create-k8s-kubelet-certs.yml

- include_tasks: create-etcd-certs.yml

# 這裡是刪除所有 .csr 及憑證設定檔 .json 若要長久使用同一憑證，這裡就不太適合刪除
# cert_info_expiry 的設定值為 87600h = 10 年
# 是否需要考慮改為 2160h = 3 月，並且定期加簽？
- include_tasks: purge-files.yml

- include_tasks: make-cert-bundle.yml