apiVersion: v1
kind: ConfigMap
metadata:
  name: go-web-app-cm
data:
  CONF: |
    tcp:
      name: tcp
      enable: false
      host: echo-server.default.svc.local:31400
      interval: 1 #ms
    http:
      name: http
      enable: false
      host: http://generic-echo-server-svc.default.svc.cluster.local:8033/echo
      interval: 1 #ms
    https:
      name: https
      enable: false
      host: echo-server.default.svc.local:8034
      interval: 1 #ms
    grpc:
      name: grpc
      enable: true
      host: generic-echo-server-svc.default.svc.cluster.local:31400
      interval: 1 #ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app-client-v1
  labels:
    app: go-web-app-client
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app-client
      version: v1
  template:
    metadata:
      labels:
        app: go-web-app-client
        version: v1
    spec:
      containers:
      - name: go-web-app-client
        image: docker.io/whitewalker0506/go_web_app_client:0.0.1
        imagePullPolicy: IfNotPresent
        args: ["-c", "/etc/generic-client/conf"]
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: client-conf
          mountPath: /etc/generic-client
      volumes:
      - name : client-conf
        configMap:
          name: go-web-app-cm
          items:
          - key: CONF
            path: conf
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-app-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  ports:
  - name: prom
    port: 5000
    targetPort: 5000
  selector:
    app: go-web-app-client
---