---
- name: Disable selinux
  command: "sed -i 's/enforcing/disabled/' /etc/selinux/config"

- name: Disable selinux temporarily
  command: 'setenforce 0'

- name: Reboot
  reboot:
    reboot_timeout: 3600
  when: reboot == 'ture'