---
# 需調整版本
kube_version: 1.20.4
etcd_version: 3.4.15

# Container runtime,
# Supported: docker, nvidia-docker, containerd, crio.
container_runtime: crio
docker_version: 19.03.9
cri_o_version: 1.19.1

# Container network,
# Supported: calico, flannel.
cni_enable: true
container_network: calico

# 需調整vip ip - vip 指的是 api server 統一對外ip(未)
# Kubernetes HA extra variables.
# vip_interface: ""
# vip_address: 10.0.1.180

# Kubernetes extra addons
enable_ingress: true
enable_dashboard: true
enable_logging: false
enable_monitoring: false
enable_metric_server: false
enable_istio: false

ansible_ssh_port: 22
ansible_ssh_private_key_file: /K8S_Ansible/sshkey/urAD-Dev
ansible_ssh_user: root

vip_address: 10.130.0.238
vip_address_2: 10.130.0.237
vip_address_3: 10.130.0.239