---
# 需調整版本
kube_version: 1.18.0

# Container runtime,
# Supported: docker, nvidia-docker, containerd.
container_runtime: docker

# Container network,
# Supported: calico, flannel.
cni_enable: true
container_network: calico

# 需調整vip ip - vip 指的是 api server 統一對外ip(未)
# Kubernetes HA extra variables.
vip_interface: ""
vip_address: 172.29.19.47

# Kubernetes extra addons
enable_ingress: false
enable_dashboard: false
enable_logging: false
enable_monitoring: false
enable_metric_server: false

ansible_ssh_port: 22
ansible_ssh_private_key_file: /K8S_Ansible/sshkey/unicorn_kubernetes_key
ansible_ssh_user: root
