---
# 需調整預設值(未)

###################
# Kubernetes opts #
###################

kube_version: 1.19.0

# Container runtime,
# Supported: docker, containerd.
container_runtime: docker

# Container network,
# Supported: calico, flannel.
cni_enable: true
container_network: calico
cni_iface: "ens.*,enp1s.*,eth.*"

# Kubernetes cluster network
pod_network_cidr: 10.244.0.0/16
cluster_subnet: 10.96.0
service_ip_range: "{{ cluster_subnet }}.0/12"
service_node_port_range: 30000-32767
api_service_ip: "{{ cluster_subnet }}.1"
cluster_dns_ip: "{{ cluster_subnet }}.10"
cluster_domain_name: cluster.local

# Kubernetes HA extra variables.
enable_keepalived: true
enable_haproxy: true

vip_address_array: 
  - 10.0.1.180
  - 10.0.1.179
  - 10.0.1.178
vip_interface: ""
vip_address: "{{ vip_address_array[0] }}"
main_vip_address: "{{ vip_address_array[0] }}"
lb_secure_port: 8443
lb_api_url: "https://{{ main_vip_address }}:{{ lb_secure_port }}"

# etcd extra variables.
etcd_iface: ""
etcd_domain_name: test.etcd.com

# Kubernetes bootstrap token
bootstrap_token_id: "6ac849"
bootstrap_token_secret: "18fac0a6405e8e15"
bootstrap_token: "{{ bootstrap_token_id }}.{{ bootstrap_token_secret }}"

# Kubernetes secret encryption
encryption_token: ZlR/e9hce4Q3qhfDShAY+rBM/hHtUOLFgCz5WK6wsmU=

# Kubernetes extra addons
# enable_ingress: false
# enable_dashboard: true
# enable_logging: false
# enable_monitoring: false
# enable_metric_server: false

ingress_lb_address: "{{ main_vip_address }}"

monitoring_lb_address: "{{ main_vip_address }}"
monitoring_grafana_user: "admin"
monitoring_grafana_password: "p@ssw0rd"

# kube-proxy variables
# Supported: iptables or ipvs.
kubeproxy_mode: iptables
kubeproxy_ipvs_scheduler: rr

###############
# Docker opts #
###############
# 這裡需要將私有docker registry 的資訊填入(未)
# A list of the insecure registry you might need to define
search_registries:
  - 'grd-dev.urad.com.tw'
#  - 'docker.io'
#insecure_registries:
# - "192.168.2.9:5000"
#block_registries:
# - 'docker.io'

# docker_opts:
# - "HTTP_PROXY=http://proxy.example.com:80/"
# - "HTTPS_PROXY=https://proxy.example.com:443/"

# Add http and https proxy
proxy_env:
  # http://:<usr>@<passwd>:<ip>:<port>
  http_proxy: ""
  # https://<usr>:<passwd>@<ip>:<port>
  https_proxy: ""

#############
# Msic opts #
#############

# Download pkg from custom URL.
repos_offline: false
repos_port: 4040
repos_offline_url: "http://172.16.35.9:{{ repos_port }}"
